version: "3"

services:
  app:
    container_name: signex_server
    build: .
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - ${SERVER_PORT}:3000
    command: sh -c "yarn && yarn dev"
    tty: true
