version: "3"

services:
  app:
    build: .
    container_name: signex_server
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./:/var/www/html
    env_file: .env
    depends_on:
      - database

  database:
    image: mysql:5.7
    container_name: signex_storage
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=America/Sao_Paulo
    volumes:
      - ./db/dump/:/docker-entrypoint-initdb.d/
    env_file: .env
    restart: always
